export const PROFESSIONAL_TITLES = [
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'Mobile App Developer',
    'UI/UX Designer',
    'Product Designer',
    'Graphic Designer',
    'Web Designer',
    'Software Engineer',
    'DevOps Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'Product Manager',
    'Project Manager',
    'Marketing Manager',
    'Content Creator',
    'Digital Marketing Specialist',
    'SEO Specialist',
    'Business Analyst',
    'Consultant',
    'Freelancer',
    'Entrepreneur',
    'Founder',
    'CEO',
    'CTO',
    'Designer',
    'Developer',
    'Engineer',
    'Architect',
    'Analyst',
    'Specialist',
    'Expert',
    'Professional',
    'Creative',
    'Innovator',
    'Visionary',
];

export const BIO_SUGGESTIONS = {
    'Full Stack Developer': [
        'Passionate full stack developer with expertise in modern web technologies. I love building scalable applications and solving complex problems.',
        'Experienced full stack developer specializing in React, Node.js, and cloud technologies. Committed to delivering high-quality, user-centric solutions.',
        'Full stack developer with a keen eye for detail and a passion for clean, efficient code. Always learning and adapting to new technologies.',
    ],
    'Frontend Developer': [
        'Creative frontend developer focused on crafting beautiful, responsive user interfaces. Expert in React, TypeScript, and modern CSS frameworks.',
        'Frontend specialist passionate about user experience and performance optimization. I transform designs into pixel-perfect, interactive web applications.',
        'Dedicated frontend developer with a love for JavaScript frameworks and CSS animations. Creating engaging digital experiences is my passion.',
    ],
    'Backend Developer': [
        'Backend developer specializing in scalable APIs and database design. I build the foundation that powers modern web applications.',
        'Experienced backend engineer with expertise in Node.js, Python, and cloud infrastructure. Focused on performance, security, and reliability.',
        'Backend specialist passionate about creating robust, efficient server-side solutions. I enjoy architecting systems that scale.',
    ],
    'UI/UX Designer': [
        'UI/UX designer with a passion for creating intuitive, beautiful digital experiences. I blend creativity with user-centered design principles.',
        'Creative designer focused on user experience and interface design. I love solving complex problems through thoughtful design solutions.',
        'UX/UI designer dedicated to crafting meaningful digital experiences. Research-driven approach with a focus on accessibility and usability.',
    ],
    'Product Designer': [
        'Product designer bridging the gap between business goals and user needs. I create products that people love to use.',
        'Strategic product designer with expertise in user research, prototyping, and design systems. Building products that matter.',
        'Product designer passionate about the entire product lifecycle. From concept to launch, I ensure every detail serves the user.',
    ],
    'Graphic Designer': [
        'Creative graphic designer with a passion for visual storytelling. I bring ideas to life through compelling visual communication.',
        'Versatile graphic designer specializing in branding, print, and digital media. Creating visuals that capture attention and convey messages.',
        'Graphic designer with expertise in Adobe Creative Suite and modern design trends. I craft visuals that tell stories and inspire action.',
    ],
    'Software Engineer': [
        'Software engineer with a passion for writing clean, maintainable code. I enjoy tackling complex problems and building innovative solutions.',
        'Experienced software engineer specializing in scalable architectures and best practices. Committed to delivering high-quality software.',
        'Software engineer focused on performance, security, and user experience. I build applications that users love and developers admire.',
    ],
    'Data Scientist': [
        'Data scientist passionate about extracting insights from complex datasets. I use statistics, machine learning, and visualization to drive decisions.',
        'Experienced data scientist with expertise in Python, R, and big data technologies. Turning data into actionable business intelligence.',
        'Data scientist focused on predictive modeling and data visualization. I help organizations make data-driven decisions.',
    ],
    'Product Manager': [
        'Product manager with a track record of launching successful products. I bridge the gap between business, technology, and user needs.',
        'Strategic product manager experienced in agile methodologies and cross-functional collaboration. Building products that customers love.',
        'Product manager passionate about user research, data analysis, and product strategy. I guide products from concept to market success.',
    ],
    'Marketing Manager': [
        'Marketing manager with expertise in digital marketing and brand strategy. I create campaigns that drive engagement and growth.',
        'Experienced marketing professional specializing in content marketing, SEO, and social media. Building brands that resonate with audiences.',
        'Strategic marketing manager focused on data-driven campaigns and customer acquisition. I help businesses grow through effective marketing.',
    ],
    'Content Creator': [
        'Creative content creator passionate about storytelling and digital media. I produce engaging content that connects with audiences.',
        'Versatile content creator with expertise in video production, writing, and social media. Creating content that inspires and entertains.',
        'Content creator focused on authentic storytelling and audience engagement. I build communities through compelling digital content.',
    ],
    'default': [
        'Passionate professional with expertise in my field. I love creating solutions that make a difference.',
        'Experienced specialist committed to excellence and continuous learning. Building meaningful connections and delivering results.',
        'Dedicated professional with a creative approach to problem-solving. I thrive on challenges and innovation.',
    ],
};

export const LOCATION_SUGGESTIONS = [
    'San Francisco, CA',
    'New York, NY',
    'Los Angeles, CA',
    'Chicago, IL',
    'Austin, TX',
    'Seattle, WA',
    'Boston, MA',
    'Denver, CO',
    'Miami, FL',
    'Atlanta, GA',
    'London, UK',
    'Paris, France',
    'Berlin, Germany',
    'Amsterdam, Netherlands',
    'Toronto, Canada',
    'Vancouver, Canada',
    'Sydney, Australia',
    'Melbourne, Australia',
    'Singapore',
    'Tokyo, Japan',
    'Dubai, UAE',
    'Mumbai, India',
    'Bangalore, India',
    'São Paulo, Brazil',
    'Mexico City, Mexico',
    'Buenos Aires, Argentina',
    'Cape Town, South Africa',
    'Lagos, Nigeria',
    'Nairobi, Kenya',
    'Cairo, Egypt',
    'Remote',
    'Worldwide',
];

export const POSITION_SUGGESTIONS = [
    'Software Engineer',
    'Senior Software Engineer',
    'Lead Software Engineer',
    'Principal Software Engineer',
    'Engineering Manager',
    'Senior Engineering Manager',
    'VP of Engineering',
    'CTO',
    'Frontend Developer',
    'Senior Frontend Developer',
    'Full Stack Developer',
    'Backend Developer',
    'DevOps Engineer',
    'Site Reliability Engineer',
    'Data Scientist',
    'Machine Learning Engineer',
    'Product Manager',
    'Senior Product Manager',
    'Product Owner',
    'Project Manager',
    'Scrum Master',
    'UX Designer',
    'UI Designer',
    'Product Designer',
    'Graphic Designer',
    'Marketing Manager',
    'Content Marketing Manager',
    'Growth Hacker',
    'Business Analyst',
    'Data Analyst',
    'Consultant',
    'Freelancer',
    'Entrepreneur',
    'Founder',
    'CEO',
    'COO',
    'CMO',
    'Intern',
    'Junior Developer',
    'Mid-level Developer',
    'Senior Developer',
    'Lead Developer',
    'Architect',
    'Technical Lead',
    'Team Lead',
];

export const DESCRIPTION_SUGGESTIONS = {
    'Software Engineer': [
        'Developed and maintained scalable web applications using modern technologies. Collaborated with cross-functional teams to deliver high-quality software solutions.',
        'Designed and implemented backend services and APIs. Focused on performance optimization, security, and maintainable code architecture.',
        'Built responsive user interfaces and interactive web applications. Worked closely with designers to ensure pixel-perfect implementations.',
    ],
    'Frontend Developer': [
        'Created responsive and interactive user interfaces using React and modern CSS frameworks. Ensured cross-browser compatibility and optimal performance.',
        'Developed component libraries and design systems for consistent UI/UX across applications. Collaborated with design teams to implement pixel-perfect designs.',
        'Built single-page applications with state management and routing. Optimized for performance and accessibility standards.',
    ],
    'Backend Developer': [
        'Designed and implemented RESTful APIs and microservices architecture. Ensured scalability, security, and high availability of backend systems.',
        'Developed database schemas and optimized queries for performance. Implemented caching strategies and background job processing.',
        'Built server-side applications with Node.js/Python frameworks. Integrated with third-party APIs and managed deployment pipelines.',
    ],
    'Product Manager': [
        'Led product development from concept to launch, managing cross-functional teams and stakeholder communication. Defined product roadmaps and prioritized features.',
        'Conducted user research and market analysis to inform product decisions. Collaborated with engineering and design teams to deliver user-centric solutions.',
        'Managed product lifecycle including requirements gathering, sprint planning, and release management. Analyzed metrics to drive product improvements.',
    ],
    'UX Designer': [
        'Conducted user research and usability testing to inform design decisions. Created wireframes, prototypes, and high-fidelity mockups.',
        'Designed user-centered interfaces and experiences. Collaborated with product and engineering teams to ensure design implementation.',
        'Developed design systems and component libraries. Ensured consistency and accessibility across digital products.',
    ],
    'default': [
        'Collaborated with cross-functional teams to deliver high-quality solutions. Focused on user needs and business objectives.',
        'Developed and implemented features that improved user experience and business metrics. Worked in agile environments with continuous delivery.',
        'Contributed to product development lifecycle from planning to deployment. Ensured quality, performance, and scalability of solutions.',
    ],
};

export const PROJECT_DESCRIPTION_SUGGESTIONS = [
    'A modern web application built with React and Node.js, featuring real-time updates and responsive design.',
    'Mobile-first e-commerce platform with integrated payment processing and inventory management.',
    'Data visualization dashboard that provides actionable insights through interactive charts and analytics.',
    'Social media platform connecting users with shared interests, featuring real-time messaging and content sharing.',
    'Learning management system with course creation tools, progress tracking, and assessment features.',
    'Portfolio website showcasing creative work with smooth animations and optimized performance.',
    'Task management application with team collaboration features and project tracking capabilities.',
    'Weather forecasting app with location-based services and detailed weather analytics.',
    'Recipe sharing platform with user-generated content, ratings, and meal planning features.',
    'Fitness tracking application with workout logging, progress charts, and social features.',
    'Real estate platform with property listings, search filters, and virtual tours.',
    'Event planning application with calendar integration, guest management, and RSVP tracking.',
    'Music streaming service with playlist creation, discovery features, and offline listening.',
    'Travel booking platform with flight and hotel search, price comparison, and booking management.',
    'Blog platform with content management, SEO optimization, and social media integration.',
    'Photo editing application with filters, effects, and export capabilities.',
    'Video conferencing tool with screen sharing, recording, and breakout rooms.',
    'Financial tracking app with expense categorization, budgeting, and reporting features.',
    'Language learning platform with interactive lessons, progress tracking, and gamification.',
    'Marketplace application connecting buyers and sellers with secure payment processing.',
];